// Zero-dependency local mock server. Mimics the /api/records CRUD routes and
// the /api/export/* routes so the React frontend can be exercised end-to-end
// without installing Azure Functions Core Tools or any npm packages first.
//
// Run with: node mock-server.js   (from inside api-node/)
// Serves on http://localhost:7071/api

const http = require('http');

let records = [
  { id: '1', name: 'Sample widget', amount: 42, createdAt: new Date().toISOString() },
  { id: '2', name: 'Sample gadget', amount: 17.5, createdAt: new Date().toISOString() },
];
let nextId = 3;

function send(res, status, body, headers = {}) {
  res.writeHead(status, { 'Access-Control-Allow-Origin': '*', ...headers });
  res.end(body);
}

function sendJson(res, status, data) {
  send(res, status, JSON.stringify(data), { 'Content-Type': 'application/json' });
}

function readBody(req) {
  return new Promise((resolve) => {
    let data = '';
    req.on('data', (chunk) => (data += chunk));
    req.on('end', () => {
      try {
        resolve(data ? JSON.parse(data) : {});
      } catch {
        resolve({});
      }
    });
  });
}

const server = http.createServer(async (req, res) => {
  const url = new URL(req.url, 'http://localhost');
  const path = url.pathname;

  // CORS preflight
  if (req.method === 'OPTIONS') {
    return send(res, 204, '', {
      'Access-Control-Allow-Methods': 'GET,POST,PUT,DELETE,OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type',
    });
  }

  if (path === '/api/records' && req.method === 'GET') {
    return sendJson(res, 200, records);
  }

  if (path === '/api/records' && req.method === 'POST') {
    const body = await readBody(req);
    if (!body.name || typeof body.amount !== 'number') {
      return sendJson(res, 400, { error: 'name and amount are required' });
    }
    const item = { id: String(nextId++), name: body.name, amount: body.amount, createdAt: new Date().toISOString() };
    records.push(item);
    return sendJson(res, 201, item);
  }

  const recordMatch = path.match(/^\/api\/records\/([^/]+)$/);
  if (recordMatch && req.method === 'PUT') {
    const id = recordMatch[1];
    const body = await readBody(req);
    const idx = records.findIndex((r) => r.id === id);
    if (idx === -1) return sendJson(res, 404, { error: 'not found' });
    records[idx] = { ...records[idx], name: body.name, amount: body.amount };
    return sendJson(res, 200, records[idx]);
  }

  if (recordMatch && req.method === 'DELETE') {
    const id = recordMatch[1];
    const before = records.length;
    records = records.filter((r) => r.id !== id);
    if (records.length === before) return sendJson(res, 404, { error: 'not found' });
    return send(res, 204, '');
  }

  // Export stubs: the real files are generated by the Python Function App.
  // These placeholders let the "Export" buttons work end-to-end locally.
  if (path === '/api/export/excel' && req.method === 'GET') {
    const csv = ['Name,Amount,Created', ...records.map((r) => `${r.name},${r.amount},${r.createdAt}`)].join('\n');
    return send(res, 200, csv, {
      'Content-Type': 'text/csv',
      'Content-Disposition': 'attachment; filename=export-mock.csv',
    });
  }

  if (path === '/api/export/pdf' && req.method === 'GET') {
    return sendJson(res, 501, {
      error: 'PDF export mock not implemented in mock-server.js — run the Python Function App (api-python) to test real PDF export.',
    });
  }

  // Invoice/Packing List/Statement generation lives entirely in api-python
  // (openpyxl/reportlab, with the company letterhead baked in) — no mock here.
  const documentExportMatch = path.match(/^\/api\/documents\/(invoice|packing-list|statement)\/(excel|pdf)$/);
  if (documentExportMatch && req.method === 'POST') {
    return sendJson(res, 501, {
      error: 'Document export mock not implemented in mock-server.js — run the Python Function App (api-python) to generate real Invoice/Packing List/Statement files.',
    });
  }

  return sendJson(res, 404, { error: 'not found' });
});

const PORT = 7071;
server.listen(PORT, () => {
  console.log(`Mock API server running at http://localhost:${PORT}/api`);
});
